### ISSUE TITLE
Translating "non-id" messages (containing spaces)

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/Translation#101]
Email copy&paste:

> Hi Filip,
> 
> First of all, thanks for the great Kdyby/Translation addon!
> 
> Being unfamiliar with any PHP web framework, I stumbled across
> something strange to me.
> ## Problem
> 
> Being unfamiliar with any PHP web framework, I just spent about an
> hour of code reading why the following code does not work:
> 
> ```
>  echo $translator->translate('messages.Have a nice day');
>  // Expected output: Schönen Tag!
>  // Actual output: messages.Have a nice day
> ```
> 
> What I found out:
> 
> If any string contains a space, it is automatically searched for in
> the `messages` domain and it does not need the `messages.` prefix.
> This is actually useful, because untranslated messages display nicer.
> 
> **However:**
> - This behaviour is not documented
> - It is not consistent
> - I think, it is different from the Symfony bundle
> 
> Does it really work as intended?
> The following code produces somewhat unexpected results:
> 
> ```
>  echo $translator->translate('labels.Drop here');
>  // Expected output: Hier loslassen
>  // Actual output: labels.Drop here
> ```
> 
> The string would actually have to be defined in `messages.de.neon`:
> 
> ```
>  # messages.de.neon
>  labels:
>      Drop here: Hier loslassen
> ```
> ## Suggestion
> 
> It would be nice, if this behaviour is documented,
> or the lookup method is enhanced.
> 
> The appropriate function is
> `Kdyby\Translation\Translator::extractMessageDomain`
> and was added in commit `1083cd0`.
> ## Thanks
> 
> Thanks for reading my mail and best regards!
> 
> Cheers,
> Adrian

**Comment by EaredSeal** [comment]
Hi, I have the same problem. But I have a solution
https://github.com/Kdyby/Translation/pull/107

**Comment by EaredSeal** [comment]
Just use the prefix "//"
eg.  echo $translator->translate('//labels.Drop here');

**Comment by fprochazka** [comment]
After reviewing the email and your PR @EaredSeal, I've concluded that this is in fact a Feature!

Using namespaces and non-id messages is not supported and probably never will be.
