### ISSUE TITLE
New stable version

### ISSUE THREAD

**Issue by enumag** [Kdyby/Translation#103]
@fprochazka Could you release a new stable version please? There are several commits forcing me to use the master version.

**Comment by JanGalek** [comment]
yes, now I have message

> User Deprecated
> 
> Invoking filters via $template->translate($vars) is deprecated, use ($vars|translate)

:)

**Comment by enumag** [comment]
Actually this was before Kdyby/Translation 2.3.0 so this issue should have been closed.

The error you mentioned seems like Nette 2.4 related? Can you send a pull request with a fix?

**Comment by JanGalek** [comment]
I don't have a fix, but I'll try fix it.

**Comment by JanGalek** [comment]
Ok, now it translated, I'll do some tests, and can send pull request
