### ISSUE TITLE
[CZ/SK] Question

### ISSUE THREAD

**Issue by FilipLukac** [Kdyby/Translation#109]
Ahoj, da sa upravit translator tak, aby tahal translaty z databazy ? popripade nejaky panel, kde by sa dali priamo pisat preklady ? (panel v zmysle v debug paneli)

**Comment by JanGalek** [comment]
na to si myslím bude lepší napsat si vlastní překladač, ten by neměl být ani moc složitý :)

**Comment by FilipLukac** [comment]
@jangalek mne ale velmi vyhovuje tento, aj jeho funkcionalita :)

**Comment by enumag** [comment]
Něco experimentálního na tahání překladů z db najdeš [tady](https://github.com/Kdyby/Translation/pull/89). Pokud jde o panel tak ten by sis musel napsat sám.

**Comment by FilipLukac** [comment]
@enumag dakujem :) akurat som cital tweet od kdybyho :) po skuskovom sa vraj nato pozrie :)

**Comment by fprochazka** [comment]
Uvidím jak to stihnu, ale databázové překlady chci vyřešit taky. Ale ideálně tak, aby to bylo zavisle jen na symfony. Každopádně, ne v tomhle repu.
