### ISSUE TITLE
Pluralization

### ISSUE THREAD

**Issue by landsman** [Kdyby/Translation#120]
Hi,

are there some solution to this?

```
{_consultation.expert.assistant, ['sex' => $e->sex]}

homepage:
    gender: 'Man|Woman'
```

**Comment by Studioartcz** [comment]
Oh, i got it:

'{0} There are no apples|{1} There is one apple|]1,19] There are %count% apples|[20,Inf[ There are many apples'

**Comment by mabar** [comment]
In documentation is link to current [symfony documentation](https://github.com/Kdyby/Translation/blob/master/docs/en/index.md#pluralization)
Please, close this issue.

**Comment by fprochazka** [comment]
@mabar thanks! I think that should be enough, right?

**Comment by nothrem** [comment]
To make it absolutely clear, this is the trick you can use to translate genders:

message.latte:
`{_message.replied, $message->gender, [name => $message->name]}`
message.neon:
`replied: "{1}%name% napsal:|{2}%name% napsala:|{3}%name% napsali:"`

Where gender is `['male' => 1, 'female' => 2, 'company' => 3]` etc.

**Comment by landsman** [comment]
@nothrem your example is not for 4 and more cases.

**Comment by mabar** [comment]
`replied: "{1}%name% napsal:|{2}%name% napsala:|{3}%name% napsali:|{4}%name% napsalo:"`
`['male' => 1, 'female' => 2, 'company' => 3, 'unknown' => 4]`

@landsman Maybe like this?
