### ISSUE TITLE
TranslationExtension: dirs are appended to defaults

### ISSUE THREAD

**Issue by greeny** [Kdyby/Translation#121]
When i configure translation extension like this:

```yaml
dirs:
	- %appDir%/lang/server
```

And then I check for what is defined in extension as dirs, i get this:

![image](https://cloud.githubusercontent.com/assets/3734204/17553493/5b7938be-5f06-11e6-9caf-1c4166b38405.png)

Obviously, I want only that one dir under key `2` in array to be scanned.

**Comment by matej21** [comment]
You can use overwrite modifier:
```yaml
dirs!:
    - foo
```

**Comment by greeny** [comment]
@matej21 nice, did not know about that
