### ISSUE TITLE
'Ž' letter problem

### ISSUE THREAD

**Issue by misaon** [Kdyby/Translation#122]
Zdarec, když mám v neon souboru s překlady následující string:
```
global:
    famale: "žena"
```
a v kódu použiji následující zápis:
`ucfirst($this->translator->translate('admin.global.famale'))`

translator **ignoruje funkci ucfirst**. U všech ostatních stringů funguje tak jak má. Mám dojem, že může být problém ve velkém písmenu **Ž** na začátku slova/věty.

**Comment by PavelJurasek** [comment]
This is rather ucfirst function problem as "ž" is multibyte. See http://php.net/manual/en/function.ucfirst.php#57298

**Comment by misaon** [comment]
Omg sorry...
Thanks
