### ISSUE TITLE
Version compatible with Nette 2.4

### ISSUE THREAD

**Issue by lupo112** [Kdyby/Translation#123]
When you will release stable version compatible with Nette 2.4?

I don't want to write my own macros for translation.

Thx.

**Comment by fprochazka** [comment]
Try master for now, it should be working. I'll do my best to release it asap. But I have to verify and do few things first.

**Comment by fprochazka** [comment]
Soon https://github.com/Kdyby/Translation/issues/129#issuecomment-301526445
