### ISSUE TITLE
Translates message, but also throws missing translation

### ISSUE THREAD

**Issue by medhi** [Kdyby/Translation#124]
If I create a flash message this way:

`$this->flashMessage(new Phrase("general.weSentPasswordRequest", ['email' => $email]));`

It translates flash message well (`{_$flash->message}`), but it also throws missing translation error in debug bar: 

Untranslated message:   general.general.weSentPasswordRequest
Translation domain: general

**Comment by fprochazka** [comment]
@medhi I've written a test case covering the case you've described, but I'm unable to reproduce it :(
