### ISSUE TITLE
What should happen when translating absolute message and providing $domain at same time?

### ISSUE THREAD

**Issue by Lexinek** [Kdyby/Translation#127]
I was thinking, what should be the result, when trying something like this:

``` php
$translator->translate("//messages.someMessage", NULL, [], "something");
```

Should the result be same as `{_messages.something.someMessage}`?

Imho throwing exception could be solution as well, what do you think @fprochazka ?

**Comment by fprochazka** [comment]
Throwing and exception seems reasonable.

**Comment by fprochazka** [comment]
This might be a BC Break, but IMHO better to break it than having undefined behaviour. It can be always defined later :)

**Comment by fprochazka** [comment]
@Lexinek thank you for reporting this!
