### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by misaon** [Kdyby/Translation#129]
Please release new version with last commits, ver. 2.3.0 havent support for nette 2.4 and i need stable dependency in composer.
Thanx.

**Comment by Olicek** [comment]
What we are waiting for?
ping @fprochazka

**Comment by landsman** [comment]
ping @fprochazka

**Comment by misaon** [comment]
Guys, any idea for alternative? I think this repo is abandoned..

**Comment by landsman** [comment]
@misaon fork?

**Comment by misaon** [comment]
i think i will fork tommorow.

**Comment by fprochazka** [comment]
FYI, it is not abandoned, I just have zero time to maintain it at this point.

**Comment by landsman** [comment]
@fprochazka what about some another contributor what can do these things and you trust him? :-)

**Comment by Olicek** [comment]
@fprochazka It would be nice to have more maintaners. I have some problems (or i require some new features) with 3 of kdyby packages.

What is your plan for next 3-6 months? Will you have some time to do some work at this packages? Or will some one who uses your packages regularly able to commits to master? This situation is realy similar to abandoned ;-)

I understand you have no time and you dont need use kdyby packages regularly. Qustion is, if it is better make some maintaner(s) or split kdyby packages to a few forks... ?

**Comment by fprochazka** [comment]
I would much rather have somebody help with with maintenance. Ideally somebody who uses the package. Forking is a solution, but imho there is no need to shatter the focus of community.

**Comment by Olicek** [comment]
@fprochazka exactly. It is my opinion also. Can i try find some people for this (ask for you, if you have no time for recruiting)?

I would like to take care of some packages, but i dont think i would be able to keep high level of kdyby code. :-(

**Comment by camohub** [comment]
Still not working.

**Comment by fprochazka** [comment]
I will release it probably today. Not sure yet, I'll have to go throught the issues first.

**Comment by fprochazka** [comment]
FYI https://filip-prochazka.com/paid-support
