### ISSUE TITLE
Dir in config with "\" not working

### ISSUE THREAD

**Issue by iNviNho** [Kdyby/Translation#130]
Hey guys,

On production server resources are not loaded if **dirs** contains `\` chars instead of `/` chars.

This didn't work:

```
translation:
    dirs: ['%appDir%\Core\lang']
```

but this works

```
translation:
    dirs: 
        - %appDir%/Core/lang
```

Maybe there should be some checking if given path is ok or not (and probably throw exception to let user know that path is invalid because it has invalid chars), what do you think?

**Comment by fprochazka** [comment]
Oh wow, this suprised me. I was sure PHP normalizes the paths.

**Comment by fprochazka** [comment]
@iNviNho thank you for reporting!

**Comment by iNviNho** [comment]
@fprochazka perfect, no problem, nice fix :)

**Comment by fprochazka** [comment]
@iNviNho please try the latest release and report if anything breaks :) Enjoy
