### ISSUE TITLE
Form values should not be translated (mostly)

### ISSUE THREAD

**Issue by medhi** [Kdyby/Translation#133]
If values of a input are dynamic, they should not be translated with form translator. But setting the input `setTranslator(NULL)` is contra productive, because it loose all other translations like labels and validations. Only case, when values should be translated by the form is if they are static (e.g. select with male/female values).

So I would appreciate a method, which will switch off translation of input's values.

**Comment by matej21** [comment]
This is nette/forms issue, see https://github.com/nette/forms/pull/58

**Comment by fprochazka** [comment]
As @matej21 mentioned, there is really nothing I can do about it.
