### ISSUE TITLE
Translation doesn't work with latte/latte 2.4.3

### ISSUE THREAD

**Issue by medhi** [Kdyby/Translation#135]
With the last update of Latte to version 2.4.3, Kdyby Translation stopped translating, because of bad domain. Looks like macro `{translator ...}` doesn't set domain properly.

**Comment by lukasojd** [comment]
+1

**Comment by fprochazka** [comment]
I've found one bug in the `{translator ...}` macro and I've updated the `{_ ...}` macro definition to be the same as the latest Latte has - https://github.com/Kdyby/Translation/commit/fbc413002547480cc92d7243142210b1505d7dcf .

Hope that fixed it, master is passing. If it's still broken, please submit a failing test case.
