### ISSUE TITLE
DB driver (branch) and the latest Nette version

### ISSUE THREAD

**Issue by Shampoo1992** [Kdyby/Translation#147]
Branch DB driver is not compatible with the latest Nette version (in my case 2.4.10).

Errors:
- Replace deprecated Nette\Object with trait Nette\SmartObject
- Invoking filters via $template->translate($vars) is deprecated, use ($vars|translate)

**Comment by enumag** [comment]
Branch db is not meant to be used. It will never be merged either since the functionality should be in a separate package. Feel free to create such package based on the code from that branch.
