### ISSUE TITLE
PhpFileStorage warning

### ISSUE THREAD

**Issue by jirirydel** [Kdyby/Translation#152]
V metodě readData($meta) v Translation/src/Caching/PhpFileStorage.php chybí datový typ parametru, viz warning.

Declaration of Kdyby\Translation\Caching\PhpFileStorage::readData($meta) should be compatible with Nette\Caching\Storages\FileStorage::readData(array $meta)

**Comment by enumag** [comment]
Duplicate of https://github.com/Kdyby/Translation/pull/149. Also fixed in nette/caching 2.5.8.
