### ISSUE TITLE
New version (4.2.0) of symfony/translation is not compatible

### ISSUE THREAD

**Issue by namo-R** [Kdyby/Translation#155]
![error](https://user-images.githubusercontent.com/22830798/49288647-9f0ad780-f4a1-11e8-96ac-3da5f6a10d76.png)

**Comment by tvaliasek** [comment]
quick fix: 
`composer require symfony/translation "4.1.8"`

**Comment by enumag** [comment]
Can someone send a PR?

By the way better hotfix is

```
composer require symfony/translation ~4.1.0
```

**Comment by petrparolek** [comment]
mají to holt v symfony rozbité

**Comment by misaon** [comment]
@petrparolek v Symfonu funguje na jedničku 😄

**Comment by enumag** [comment]
Fixed in v2.5.2.

Some of the deprecated interfaces, classes and methods are still used. Send PRs to help fix this.
