### ISSUE TITLE
Error with latte/latte 2.5.1 

### ISSUE THREAD

**Issue by BigOHenry** [Kdyby/Translation#159]
Hello, 
after update latte/latte to 2.5.1 getting this error:
`Declaration of Kdyby\StrictObjects\Scream::__call($name, $args) should be compatible with Latte\Macros\MacroSet::__call(string $name, array $args)`

Could you look at it please?
Thank you

**Comment by Roman3349** [comment]
Workaround: add `"kdyby/strict-objects": "dev-master as 1.0.1"` to dependencies in your composer file. Currently it will show warning `Declaration of Kdyby\StrictObjects\Scream::__get(string $name) should be compatible with & Nette\DI\CompilerExtension::__get($name)`, but it is fixed by my PR Kdyby/StrictObjects#8.

**Comment by dg** [comment]
Solution is to remove `use \Kdyby\StrictObjects\Scream;` from class TranslateMacros .

**Comment by petrparolek** [comment]
Doesn't class Scream need? :o

**Comment by dg** [comment]
No, because its ancestor already uses it.

**Comment by suchoproduction** [comment]
Current provisory solution

```
"repositories": [
    { "type": "vcs", "url": "https://github.com/lulco/Translation.git" }
],
"require": {
    ...
    "kdyby/translation": "dev-fix-translate-macros",
    "symfony/translation": "~4.1.0"
}
```

**Comment by petrofcikmatus** [comment]
Hi Guys, when do you want to release fix for this issue? Thank you!

**Comment by Isigar** [comment]
Ehm?

**Comment by jankonas** [comment]
I believe that the fix will be released after some PR that does not break tests appears ;-)

**Comment by jankonas** [comment]
I just submitted PR which does not break tests, but I have a concern about the minimal Latte version compatibility if this PR will be merged. Please see #164 and comment if you have some insight.
