### ISSUE TITLE
selective loading of dumpers, loaders, extractors

### ISSUE THREAD

**Issue by bazo** [Kdyby/Translation#58]
i'm profiling my app with xdebug. creation of Translation.default service takes around 40ms on my machine in production mode.

I would say this is quite a lot, since I use only neon loader, no extractors, and dumpers.
each of the loaders gets initialized on service creation which i think is not necessary.

so therefore i propose to selectively load only desired loaders, since most apps usually use only one format of catalogue files.

**Comment by fprochazka** [comment]
Fixed?
